# docker compose run --rm rhc bash
version: "3.8"
services:
  rhc:
    build: .
    volumes:
      - ./ruby:/home/rubydev/workdir/ruby
    working_dir: /home/rubydev/workdir
    stdin_open: true
    tty: true
