# docker compose run --rm rhc bash
version: "3.8"
services:
  rhc:
    build: .
    volumes:
      - ./ruby:/home/rubydev/workdir/ruby
      - ./src:/home/rubydev/workdir/src # テスト用のコードをホストから編集するためのvolume
      - build-ruby:/home/rubydev/workdir/build
      - install-ruby:/home/rubydev/workdir/install # インストールする先のディレクトリ
    working_dir: /home/rubydev/workdir
    stdin_open: true
    tty: true
volumes:
  build-ruby:
  install-ruby:

